name: dospace
description: Client library to interact with the DigitalOcean Spaces API. Same API as Amazon AWS S3.
version: 0.13.0
homepage: https://github.com/nbspou/dospace

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http: ^0.13.3
  xml: ^5.2.0

dev_dependencies:
  test: ^1.17.12
  ini: ^2.1.0